### ISSUE TITLE
mall:check not updated after 1.1.0 categories/category

### ISSUE THREAD

**Issue by timconsidine** [OFFLINE-GmbH/oc-mall-plugin#139]
php artisan mall:check on V1.1.3 returns
```
  [Illuminate\Database\Eloquent\RelationNotFoundException]                           
  Call to undefined relationship [category] on model [OFFLINE\Mall\Models\Product]. 
```

**Comment by tobias-kuendig** [comment]
Thank you for the bug report! This is fixed in v1.1.4.

**Comment by timconsidine** [comment]
Wow - thanks for rapid fix

I’m not sure if this next is a bug or my stupidity, so I didn’t raise it as an issue.

I configured a product and a shipping method, all without taxes, and not including taxes.
I then added taxes to the payment method, one for USA, one for UK and one for Netherlands.
But the checkout does not calculate taxes, either included or additional.
It shows line for correct country and correct rate, but amount is zero always.
Is this an issue or my bad configuration ?

Best wishes



Tim

**Comment by timconsidine** [comment]
Sorry - just released that the taxes in Payments Method only applies to any fees charged.
Problem remains that if I have taxes for different countries, 1 for UK, 1 for USA etc, then *all* the taxes get applied to the product.  There is no check for shipping address, like there is for shipping charge.
Is this a bug ?
or I again made a mistake ?

Best wishes



Tim

**Comment by tobias-kuendig** [comment]
Thank you. I'll have to look into this. I've created a separate issue to track progress.

https://github.com/OFFLINE-GmbH/oc-mall-plugin/issues/141
