### ISSUE TITLE
running unit test

### ISSUE THREAD

**Issue by chrisvidal** [OFFLINE-GmbH/oc-mall-plugin#194]
I am trying to run the unit tests and i fall into this error:

```
PHP Fatal error:  Uncaught Error: Class 'PluginTestCase' not found in /Users/xxxccc/Sites/oc-mall/plugins/offline/mall/tests/PluginTestCase.php:8
```

**Comment by tobias-kuendig** [comment]
You need to run the tests in the context of an October installation. See https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/develop/.travis.yml#L19

**Comment by chrisvidal** [comment]
I dam not sure to understand

I am running

```
phpunit
```

from the Mall plugin folder

**Comment by tobias-kuendig** [comment]
Run `../../../vendor/bin/phpunit` from the mall plugin folder. Make sure to have the plugin installed in October. You cannot run the tests without having a working October installation surrounding it.

**Comment by chrisvidal** [comment]
ok thanks
So October Installation done from the install does not allow to run the tests.

So I copied and installed the composer for October at his root and run the test as you mentioned.

Now I have a load of errors that looks like this:

```
PHPUnit 5.7.27 by Sebastian Bergmann and contributors.

Illuminate\Database\QueryException {#5782
  #sql: "select "offline_mall_categories".*, "offline_mall_category_product"."product_id" as "pivot_product_id", "offline_mall_category_product"."category_id" as "pivot_category_id", "offline_mall_category_product"."sort_order" as "pivot_sort_order" from "offline_mall_categories" inner join "offline_mall_category_product" on "offline_mall_categories"."id" = "offline_mall_category_product"."category_id" where "offline_mall_category_product"."product_id" = ? and "offline_mall_categories"."deleted_at" is null order by "nest_left" asc"
  #bindings: array:1 [
    0 => 1
  ]
  #message: "SQLSTATE[HY000]: General error: 1 no such table: offline_mall_category_product (SQL: select "offline_mall_categories".*, "offline_mall_category_product"."product_id" as "pivot_product_id", "offline_mall_category_product"."category_id" as "pivot_category_id", "offline_mall_category_product"."sort_order" as "pivot_sort_order" from "offline_mall_categories" inner join "offline_mall_category_product" on "offline_mall_categories"."id" = "offline_mall_category_product"."category_id" where "offline_mall_category_product"."product_id" = 1 and "offline_mall_categories"."deleted_at" is null order by "nest_left" asc)"
  #code: "HY000"
  #file: "/Users/christophevidal/Sites/oc-eclia/vendor/laravel/framework/src/Illuminate/Database/Connection.php"
  #line: 664
  -previous: Doctrine\DBAL\Driver\PDOException {#5781
    -errorCode: 1
    -sqlState: "HY000"
    #message: "SQLSTATE[HY000]: General error: 1 no such table: offline_mall_category_product"
    #code: "HY000"
    #file: "/Users/christophevidal/Sites/oc-eclia/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php"
    #line: 79
    -previous: PDOException {#5784
      #message: "SQLSTATE[HY000]: General error: 1 no such table: offline_mall_category_product"
      #code: "HY000"
      #file: "/Users/christophevidal/Sites/oc-eclia/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php"
      #line: 77
      +errorInfo: array:3 [
        0 => "HY000"
        1 => 1
        2 => "no such table: offline_mall_category_product"
      ]

```

**Comment by chrisvidal** [comment]
my database config file looks like:

```

        'mysql' => [
            'driver'    => 'mysql',
            'host'      => '127.0.0.1',
            'port'      => 3306,
            'database'  => 'oc-eclia',
            'username'  => 'abc',
            'password'  => 'xyx',
            'charset'   => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix'    => '',
        ],

```

**Comment by tobias-kuendig** [comment]
Did you run `php artisan october:up`?

You can follow these steps and you'll end up with a working environment:
https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/develop/.travis.yml#L19

**Comment by chrisvidal** [comment]
yes I did

```
Christophes-MacBook-Pro:mall christophevidal$ ../../../vendor/bin/phpunit
PHPUnit 5.7.27 by Sebastian Bergmann and contributors.

Illuminate\Database\QueryException {#5782
  #sql: "select "offline_mall_categories".*, "offline_mall_category_product"."product_id" as "pivot_product_id", "offline_mall_category_product"."category_id" as "pivot_category_id", "offline_mall_category_product"."sort_order" as "pivot_sort_order" from "offline_mall_categories" inner join "offline_mall_category_product" on "offline_mall_categories"."id" = "offline_mall_category_product"."category_id" where "offline_mall_category_product"."product_id" = ? and "offline_mall_categories"."deleted_at" is null order by "nest_left" asc"
  #bindings: array:1 [
    0 => 1
  ]
  #message: "SQLSTATE[HY000]: General error: 1 no such table: offline_mall_category_product (SQL: select "offline_mall_categories".*, "offline_mall_category_product"."product_id" as "pivot_product_id", "offline_mall_category_product"."category_id" as "pivot_category_id", "offline_mall_category_product"."sort_order" as "pivot_sort_order" from "offline_mall_categories" inner join "offline_mall_category_product" on "offline_mall_categories"."id" = "offline_mall_category_product"."category_id" where "offline_mall_category_product"."product_id" = 1 and "offline_mall_categories"."deleted_at" is null order by "nest_left" asc)"
  #code: "HY000"
  #file: "/Users/christophevidal/Sites/oc-eclia/vendor/laravel/framework/src/Illuminate/Database/Connection.php"
  #line: 664
  -previous: Doctrine\DBAL\Driver\PDOException {#5781
    -errorCode: 1
    -sqlState: "HY000"
    #message: "SQLSTATE[HY000]: General error: 1 no such table: offline_mall_category_product"
    #code: "HY000"
    #file: "/Users/christophevidal/Sites/oc-eclia/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php"
    #line: 79
    -previous: PDOException {#5784
      #message: "SQLSTATE[HY000]: General error: 1 no such table: offline_mall_category_product"
      #code: "HY000"
      #file: "/Users/christophevidal/Sites/oc-eclia/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php"
      #line: 77
      +errorInfo: array:3 [
        0 => "HY000"
        1 => 1
        2 => "no such table: offline_mall_category_product"
      ]

```

**Comment by tobias-kuendig** [comment]
This has been fixed in 8fcde28. Thanks for reporting the issue!

**Comment by tobias-kuendig** [comment]
Were you able to run the unit tests?

**Comment by chrisvidal** [comment]
nope, still the same issues

**Comment by chrisvidal** [comment]
are the unit tests using another database config file than the OC one?

**Comment by tobias-kuendig** [comment]
No it should re-use your existing database.

Have you tried executing the steps from the travis build script one after the other in an empty directory? This should get you a working set-up. Since it runs on every push we do to this repo I'm certain this will work:

```bash
mysql -e 'CREATE DATABASE IF NOT EXISTS october;'
git clone https://github.com/octobercms/october.git
mkdir -p ./october/plugins/offline/mall
cd october
composer self-update
composer install --no-interaction --prefer-source
php artisan october:env
php artisan key:generate
echo "DB_HOST=127.0.0.1" > .env
echo "DB_DATABASE=october" >> .env
echo "DB_USERNAME=root" >> .env
echo "DB_PASSWORD=" >> .env
php artisan october:up -v
php artisan plugin:install RainLab.Translate
php artisan plugin:install RainLab.User
php artisan plugin:install RainLab.Location
cd ..
mv !(october) october/plugins/offline/mall
cd october
php artisan october:up -v
cd plugins/offline/mall
composer install
# finally, run tests
../../../vendor/bin/phpunit

**Comment by chrisvidal** [comment]
this command does not pass

```
mv !(october) october/plugins/offline/mall
```

and I dont see the command to clone the Mall plugin?

**Comment by chrisvidal** [comment]
the APP KEY generation does not seem to be working properly.
The env file is not updated with it

**Comment by chrisvidal** [comment]
after fixing manually this, I tried to run the php unit

```
../../../vendor/bin/phpunit
PHP Fatal error:  Uncaught Error: Class 'PHPUnit_TextUI_Command' not found in /Users/christophevidal/Sites/oc-eclia/vendor/phpunit/phpunit/phpunit:52
Stack trace:
#0 {main}
  thrown in /Users/christophevidal/Sites/oc-eclia/vendor/phpunit/phpunit/phpunit on line 52

Fatal error: Uncaught Error: Class 'PHPUnit_TextUI_Command' not found in /Users/christophevidal/Sites/oc-eclia/vendor/phpunit/phpunit/phpunit:52
Stack trace:
#0 {main}
  thrown in /Users/christophevidal/Sites/oc-eclia/vendor/phpunit/phpunit/phpunit on line 52

```

**Comment by tobias-kuendig** [comment]
> mv !(october) october/plugins/offline/mall

This command depends on what shell you are using. You can also run

```
mv october/* .
mv october/.* .
```

> and I dont see the command to clone the Mall plugin?

I have updated the script in the comment above. Travis clones this on build so it was missing from the script.

I just verified that everyhing works as expected on my dev machine. What version of phpunit is executed when you run 

```
../../../vendor/bin/phpunit --version
```

According to this ticket you might have a mixup of different phpunit versions:
https://github.com/sebastianbergmann/phpunit/issues/2884

**Comment by chrisvidal** [comment]
```
../../../vendor/bin/phpunit --version
```
give the same previous error

if I run 
```
phpunit
```

it gives me 
```
phpunit --version
PHPUnit 8.1.3 by Sebastian Bergmann and contributors.
```

**Comment by chrisvidal** [comment]
I uninstall my global phpunit 8.3 and run the command again;
but still get the same error

I keep exploring

```
../../../vendor/bin/phpunit
PHP Fatal error:  Uncaught Error: Class 'PHPUnit_TextUI_Command' not found in /Users/christophevidal/Sites/oc-eclia/vendor/phpunit/phpunit/phpunit:52
Stack trace:
#0 {main}
  thrown in /Users/christophevidal/Sites/oc-eclia/vendor/phpunit/phpunit/phpunit on line 52

Fatal error: Uncaught Error: Class 'PHPUnit_TextUI_Command' not found in /Users/christophevidal/Sites/oc-eclia/vendor/phpunit/phpunit/phpunit:52
Stack trace:
#0 {main}
  thrown in /Users/christophevidal/Sites/oc-eclia/vendor/phpunit/phpunit/phpunit on line 52
```

**Comment by chrisvidal** [comment]
well, i really dont understand.
I forced a OC composer update with `sudo` and now the `../../../vendor/bin/phpunit` is running properly

**Comment by tobias-kuendig** [comment]
I have just noticed something:

Don't run `composer install` from the plugin's directory. Remove any vendor folder in `plugins/offline/mall` and in the root directory as well.

Now run composer install from the root directory. This solves the problem for me.
