### ISSUE TITLE
Latest Update Breaks the Plugin.

### ISSUE THREAD

**Issue by StanleyBonhomme** [OFFLINE-GmbH/oc-mall-plugin#270]
Just updated the plugin and the latest update breaks the plugin. When you click on orders in the navigation then click on any of the orders for more details it renders this error ( See Attachment). Any idea why this happens?
![screencapture-anikajasmine-test-backend-offline-mall-orders-show-10-2019-07-01-12_41_56](https://user-images.githubusercontent.com/30869347/60453057-0aff1b00-9bfe-11e9-9afb-d534fea5f09d.png)

**Comment by tobias-kuendig** [comment]
Thank you very much for this bug report, @StanleyBonhomme. Can you confirm that the issue is solved in version 1.3.12?

**Comment by StanleyBonhomme** [comment]
Hey there, just tried the latest update and I still get an error when clicking on the orders to view more details (see attachment)
![screencapture-anikajasmine-beta-backend-offline-mall-orders-show-13-2019-07-02-01_26_49](https://user-images.githubusercontent.com/30869347/60484793-b349c980-9c68-11e9-9a37-03d494de2732.png)

**Comment by tobias-kuendig** [comment]
Thank you! What payment providers do you use?

**Comment by StanleyBonhomme** [comment]
Only using Stripe

**Comment by tobias-kuendig** [comment]
Thank you, I was able to reproduce the issue. 1.3.13 should fix it for good!

**Comment by tobias-kuendig** [comment]
I'm closing this issue. Please report back if you still experience problems.

**Comment by StanleyBonhomme** [comment]
Its work now with no problem. Thanks for your help!
